<option value="US">Estados Unidos</option>
<!--<option value="AF">Afganistán</option>-->
<!--<option value="AL">Albania</option>-->
<option value="DE">Alemania</option>
<!--<option value="AD">Andorra</option>-->
<!--<option value="AO">Angola</option>-->
<!--<option value="AI">Anguila</option>-->
<!--<option value="AQ">Antártida</option>-->
<!--<option value="AG">Antigua y Barbuda</option>-->
<!--<option value="AN">Antillas Holandesas</option>-->
<!--<option value="SA">Arabia Saudita</​​option>-->
<!--<option value="DZ">Argelia</option>-->
<option value="AR">Argentina</option>
<!--<option value="AM">Armenia</option>-->
<!--<option value="AW">Aruba</option>-->
<option value="AU">Australia</option>
<option value="AT">Austria</option>
<!--<option value="AZ">Azerbaiyán</option>-->
<!--<option value="BS">Bahamas</option>-->
<!--<option value="BH">Bahrein</option>-->
<!--<option value="BD">Bangladesh</option>-->
<!--<option value="BB">Barbados</option>-->
<!--<option value="BE">Bélgica</option>-->
<!--<option value="BZ">Belice</option>-->
<!--<option value="BJ">Benín</option>-->
<!--<option value="BM">Bermuda</option>-->
<!--<option value="BT">Bhután</option>-->
<!--<option value="BY">Bielorrusia</option>-->
<!--<option value="BO">Bolivia</option>-->
<!--<option value="BA">Bosnia y Herzegowina</option>-->
<!--<option value="BW">Botswana</option>-->
<option value="BR">Brasil</option>
<!--<option value="BN">Brunei Darussalam</option>-->
<!--<option value="BG">Bulgaria</option>-->
<!--<option value="BF">Burkina Faso</option>-->
<!--<option value="BI">Burundi</option>-->
<!--<option value="CV">Cabo Verde</option>-->
<!--<option value="KH">Camboya</option>-->
<!--<option value="CM">Camerún</option>-->
<option value="CA">Canadá</option>
<!--<option value="TD">Chad</option>-->
<!--<option value="CL">Chile</option>-->
<!--<option value="CN">China</option>-->
<!--<option value="CY">Chipre</option>-->
<!--<option value="CX">Christmas Island</option>-->
<option value="CO">Colombia</option>
<!--<option value="KM">Comoras</option>-->
<!--<option value="CG">Congo</option>-->
<!--<option value="CI">Costa de Marfil</option>-->
<!--<option value="CR">Costa Rica</option>-->
<!--<option value="HR">Croacia</option>-->
<!--<option value="CU">Cuba</option>-->
<option value="DK">Dinamarca</option>
<!--<option value="DJ">Djibouti</option>-->
<!--<option value="DM">Dominica</option>-->
<!--<option value="EC">Ecuador</option>-->
<!--<option value="EG">Egipto</option>-->
<!--<option value="SV">El Salvador</option>-->
<!--<option value="AE">Emiratos Árabes Unidos</option>-->
<!--<option value="ER">Eritrea</option>-->
<!--<option value="SK">Eslovaquia</option>-->
<!--<option value="SI">Eslovenia</option>-->
<option value="ES">España</option>
<!--<option value="EE">Estonia</option>-->
<!--<option value="ET">Etiopía</option>-->
<!--<option value="FJ">Fiji</option>-->
<!--<option value="PH">Filipinas</option>-->
<!--<option value="FI">Finlandia</option>-->
<option value="FR">Francia</option>
<!--<option value="GA">Gabón</option>-->
<!--<option value="GM">Gambia</option>-->
<!--<option value="GE">Georgia</option>-->
<!--<option value="GH">Ghana</option>-->
<!--<option value="GI">Gibraltar</option>-->
<!--<option value="GD">Granada</option>-->
<!--<option value="GR">Grecia</option>-->
<!--<option value="GL">Groenlandia</option>-->
<!--<option value="GP">Guadalupe</option>-->
<!--<option value="GU">Guam</option>-->
<option value="GT">Guatemala</option>
<!--<option value="GF">Guayana Francesa</option>-->
<!--<option value="GN">Guinea</option>-->
<!--<option value="GQ">Guinea Ecuatorial</option>-->
<!--<option value="GW">Guinea-Bissau</option>-->
<!--<option value="GY">Guyana</option>-->
<!--<option value="HT">Haití</option>-->
<option value="NL">Holanda, Países Bajos</option>
<!--<option value="HN">Honduras</option>-->
<!--<option value="HK">Hong Kong</option>-->
<!--<option value="HU">Hungría</option>-->
<!--<option value="IN">India</option>-->
<!--<option value="ID">Indonesia</option>-->
<!--<option value="IR">Irán</option>-->
<!--<option value="IQ">Iraq</option>-->
<!--<option value="IE">Irlanda</option>-->
<!--<option value="BV">Isla de Bouvet</option>-->
<!--<option value="NF">Isla Norfolk</option>-->
<!--<option value="IS">Islandia</option>-->
<!--<option value="KY">Islas Caimán</option>-->
<!--<option value="CC">Islas Cocos (Keeling)</option>-->
<!--<option value="CK">Islas Cook</option>-->
<!--<option value="FO">Islas Feroe</option>-->
<!--<option value="GS">Islas Georgias del Sur y Sandwich del Sur</option>-->
<!--<option value="HM">Islas Heard y Mc Donald</option>-->
<!--<option value="FK">Islas Malvinas (Falkland Islands)</option>-->
<!--<option value="MP">Islas Marianas del Norte</option>-->
<!--<option value="MH">Islas Marshall</option>-->
<!--<option value="UM">Islas menores alejadas de los Estados Unidos</option>-->
<!--<option value="SB">Islas Salomón</option>-->
<!--<option value="SJ">Islas Svalbard y Jan Mayen</option>-->
<!--<option value="TC">Islas Turcas y Caicos</option>-->
<!--<option value="VG">Islas Vírgenes (británicas)</option>-->
<!--<option value="VI">Islas Vírgenes (EE. UU.)</option>-->
<!--<option value="WF">Islas Wallis y Futuna</option>-->
<!--<option value="IL">Israel</option>-->
<option value="IT">Italia</option>
<!--<option value="LY">Jamahiriya Árabe Libia</option>-->
<!--<option value="JM">Jamaica</option>-->
<!--<option value="JP">Japón</option>-->
<!--<option value="JO">Jordania</option>-->
<!--<option value="KZ">Kazajistán</option>-->
<!--<option value="KE">Kenya</option>-->
<!--<option value="KG">Kirguistán</option>-->
<!--<option value="KI">Kiribati</option>-->
<!--<option value="KW">Kuwait</option>-->
<!--<option value="LS">Lesotho</option>-->
<!--<option value="LV">Letonia</option>-->
<!--<option value="LB">Líbano</option>-->
<!--<option value="LR">Liberia</option>-->
<!--<option value="LI">Liechtenstein</option>-->
<!--<option value="LT">Lituania</option>-->
<!--<option value="LU">Luxemburgo</option>-->
<!--<option value="MO">Macau</option>-->
<!--<option value="MK">Macedonia</option>-->
<!--<option value="MG">Madagascar</option>-->
<!--<option value="MY">Malasia</option>-->
<!--<option value="MW">Malawi</option>-->
<!--<option value="MV">Maldivas</option>-->
<!--<option value="ML">Mali</option>-->
<!--<option value="MT">Malta</​​option>-->
<!--<option value="MA">Marruecos</option>-->
<!--<option value="MQ">Martinica</option>-->
<!--<option value="MU">Mauricio</option>-->
<!--<option value="MR">Mauritania</option>-->
<option value="MX">México</option>
<!--<option value="YT">Mayotte</option>-->
<!--<option value="MX">México</option>-->
<!--<option value="FM">Micronesia, estados federados de</option>-->
<!--<option value="MC">Monaco</option>-->
<!--<option value="MD">Moldavia</option>-->
<!--<option value="MN">Mongolia</option>-->
<!--<option value="MS">Montserrat</option>-->
<!--<option value="MZ">Mozambique</option>-->
<!--<option value="MM">Myanmar</option>-->
<!--<option value="NA">Namibia</option>-->
<!--<option value="NR">Nauru</option>-->
<!--<option value="NP">Nepal</option>-->
<!--<option value="NI">Nicaragua</option>-->
<!--<option value="NE">Níger</option>-->
<!--<option value="NG">Nigeria</option>-->
<!--<option value="NU">Niue</option>-->
<option value="NO">Noruega</option>
<!--<option value="NC">Nueva Caledonia</option>-->
<!--<option value="NZ">Nueva Zelanda</option>-->
<!--<option value="OM">Omán</option>-->
<!--<option value="PK">Pakistán</option>-->
<!--<option value="PW">Palau</option>-->
<!--<option value="PA">Panamá</option>-->
<!--<option value="PG">Papua Nueva Guinea</option>-->
<!--<option value="PY">Paraguay</option>-->
<option value="PE">Perú</option>
<!--<option value="PN">Pitcairn</option>-->
<!--<option value="PF">Polinesia Francesa</option>-->
<option value="PL">Polonia</option>
<!--<option value="PT">Portugal</option>-->
<option value="PR">Puerto Rico</option>
<!--<option value="QA">Qatar</option>-->
<!--<option value="GB">Reino Unido</option>-->
<!--<option value="SY">República Árabe Siria</option>-->
<!--<option value="CF">República Centroafricana</option>-->
<!--<option value="CZ">República Checa</option>-->
<!--<option value="KR">República de Corea</option>-->
<!--<option value="CD">República del Congo</option>-->
<!--<option value="KP">República Democrática de Corea</option>-->
<!--<option value="LA">República Democrática Popular Lao</option>-->
<option value="DO">República Dominicana</option>
<!--<option value="RE">Reunion</option>-->
<!--<option value="RW">Ruanda</option>-->
<!--<option value="RO">Rumania</option>-->
<option value="RU">Rusia</option>
<!--<option value="EH">Sáhara Occidental</option>-->
<!--<option value="KN">Saint Kitts y Nevis</option>-->
<!--<option value="WS">Samoa</option>-->
<!--<option value="AS">Samoa Americana</option>-->
<!--<option value="SM">San Marino</option>-->
<!--<option value="VC">San Vicente y las Granadinas</option>-->
<!--<option value="LC">Santa LUCIA</option>-->
<!--<option value="VA">Santa Sede (Estado de la Ciudad del Vaticano)</option>-->
<!--<option value="ST">Santo Tomé y Príncipe</option>-->
<!--<option value="SN">Senegal</option>-->
<!--<option value="SC">Seychelles</option>-->
<!--<option value="SL">Sierra Leona</option>-->
<!--<option value="SG">Singapur</option>-->
<!--<option value="SO">Somalia</option>-->
<!--<option value="LK">Sri Lanka</option>-->
<!--<option value="SH">St. Helena</option>-->
<!--<option value="PM">St. Pierre y Miquelon</option>-->
<!--<option value="ZA">Sudáfrica</option>-->
<!--<option value="SD">Sudán</option>-->
<option value="SE">Suecia</option>
<option value="CH">Suiza</option>
<!--<option value="SR">Suriname</option>-->
<!--<option value="SZ">Swazilandia</option>-->
<!--<option value="TH">Tailandia</option>-->
<!--<option value="TW">Taiwán, Provincia de China</option>-->
<!--<option value="TZ">Tanzania, República Unida de</option>-->
<!--<option value="TJ">Tayikistán</option>-->
<!--<option value="IO">Territorio Británico del Océano Índico</option>-->
<!--<option value="TF">Territorios Australes Franceses</option>-->
<!--<option value="TP">Timor Oriental</option>-->
<!--<option value="TG">Togo</option>-->
<!--<option value="TK">Tokelau</option>-->
<!--<option value="TO">Tonga</option>-->
<!--<option value="TT">Trinidad y Tobago</option>-->
<!--<option value="TN">Túnez</option>-->
<!--<option value="TM">Turkmenistán</option>-->
<option value="TR">Turquía</option>
<!--<option value="TV">Tuvalu</option>-->
<!--<option value="UA">Ucrania</option>-->
<!--<option value="UG">Uganda</option>-->
<option value="UY">Uruguay</option>
<!--<option value="UZ">Uzbekistán</option>-->
<!--<option value="VU">Vanuatu</option>-->
<!--<option value="VE">Venezuela</option>-->
<!--<option value="VN">Viet Nam</option>-->
<!--<option value="YE">Yemen</option>-->
<!--<option value="YU">Yugoslavia</option>-->
<!--<option value="ZM">Zambia</option>-->
<!--<option value="ZW">Zimbabwe</option>-->